[package]
name = "aoc-2023-04"
version = "0.1.0"
authors = ["Mårten Kongstad <marten.kongstad@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
aoc = { path = "../../aoc" }
regex = "1.10.2"
