[package]
name = "aoc-2024-06"
version = "0.1.0"
authors = ["Mårten Kongstad <marten.kongstad@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
aoc = { path = "../../aoc" }
rustc-hash = "2.1.0"
