[package]
name = "aoc-2022-19"
version = "0.1.0"
authors = ["Mårten Kongstad <marten.kongstad@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.66"
rayon = "1.6.1"
regex = "1.7.0"
rustc-hash = "1.1.0"
