[package]
name = "aoc-2022-19"
version = "0.1.0"
authors = ["Mårten Kongstad <marten.kongstad@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.75"
aoc = { version = "0.1.0", path = "../../aoc" }
rayon = "1.8.0"
regex = "1.10.2"
rustc-hash = "1.1.0"
